---
output: html_document
---

<!-- activity 1 -->

Noise is a problem for at least two reasons. First, if the noise overwhelms the signal, then the signal becomes invisible. Second, even if the signal is visible, noise superimposed on the signal adds uncertainty to the analyte's signal.

#### How Do We Measure the Signal and the Noise?

The most common way to measure an analyte's signal, $S_\text{analyte}$, is to choose a wavelength that includes the signal and record the absorbance. The vertical line at 630 nm serves this purpose.

A1.1. Why is 630 nm an appropriate wavelength to use? What problems, if any, arise if we use 500 nm or 600 nm?

The most common way to measure noise is to calculate the standard deviation for a range of wavelengths, $s_\text{noise}$. The rectangular box from 700--775 nm serves this purpose.

A1.2. Why is 700--775 nm an appropriate range of wavelengths to use? What problems, if any, arise if we use 600--650 nm or 800--900 nm?

#### How Do We Report the Signal and the Noise?

The absorbance spectrum on the right reports the signal and the noise as described above. The signal is always of interest to us as it provides information about the analyte's concentration. The absolute amount of noise usually is of little interest to us; however the amount of noise relative to the signal, called the signal-to-noise ratio, $S/N$, is important as it is a measurement of the uncertainty in the signal.

$$S/N = S_\text{analyte} / s_\text{noise}$$

A1.3. Use the slider to examine some or all of the 64 individual absorbance spectra in this data set. Pay attention to variations in the signal-to-noise ratios between spectra, all of which were obtained at the same time and under the same conditions. How much variation is there in the signal-to-noise ratio? What is the largest value? What is the smallest value? Are most values in the center of this range, or is the distribution more uniform?
