---
output: html_document
---

<!-- activity 2 -->

The signal-to-noise ratio affects our ability to answer two questions at the heart of many analytical measurements: Is the analyte present, and, if yes, at what concentration? The figure to the right shows the result of an analytical measurement that yields a peak. The specific source of the data is not important; indeed, this is purely synthetic data. The signal, noise, and signal-to-noise ratio are reported above the peak. The two sliders allow you to increase and decrease the signal and the noise, and thus, to vary the signal-to-noise ratio.

#### Qualitative Judgements Using the Signal-to-Noise Ratio

A qualitative analysis is a binary decision. Are we confident---yes or no---that the analyte is present?

A2,1. Use the two sliders to identify a threshold signal-to-noise ratio above which you are confident that a peak is present. Is your threshold the same if you approach it from a larger or from a smaller signal-to-noise ratio?

A2.2. If the noise follows a normal distribution, we expect that 96% of the noise is within two standard deviations of the mean, and we expect that 99% of the noise is within three standard deviations. Is your threshold signal-to-noise ratio consistent with this?

#### Quantitative Judgements Using the Signal-to-Noise Ratio

For a quantitative analysis we want to minimize any uncertainty in our measurement of the signal.

A2.3. Use the two sliders to identify a threshold signal-to-noise ratio above which you are confident that the noise is not significantly affecting your measurement of the signal. Is your threshold the same if you approach it from a larger or from a smaller signal-to-noise ratio?

A2.4. How does your qualitative threshold compare to your quantitative threshold? Are they relatively similar to each other, or are they quite different? Are you comfortable with this difference?
