---
output: html_document
---

<!-- introduction -->

The figure to the right shows replicate visible spectra for a very dilute solution of a blue dye, which is our analyte. All spectra have the same *x*-axis and *y*-axis scales, which are included with the spectra in the lower right and upper left corners, respectively. Eight individual spectra are arranged on the outside (in blue); the central figure (in magenta) overlays 64 individual spectra.

Each spectrum in this data set has two parts: a determinate, or fixed contribution from the analyte and an indeterminate, or random contribution from uncertainty in the measurement process. The first is the signal and the second is the noise. 

#### Describing the Signal

The spectra are nearly identical: each has a prominent absorbance peak at about 630 nm with a maximum absorbance of roughly 0.025 absorbance units (au). The absorbance peaks are nearly symmetrical in shape, with a possible shoulder at shorter wavelengths. Each spectrum has a width at half-height of approximately 45 nm. The similarity in these features means the spectra contain useful information about the analyte in the form of its peak position, peak shape, and absorbance. Any additional spectra should share these features. This is what it means to say that a spectrum includes a systematic analytical signal.

#### Describing the Noise

The spectra also share a background absorbance on either side of the peak, characterized by absorbance values less than 0.005 au  that fluctuate by approximately ±0.0025 au. These fluctuations are random and do not have an underlying systematic pattern that carries information about the analyte; the fluctuations, however, carry information about the method by which the spectra were recorded. Any additional spectra should share these features. This is what it means to say that a spectrum contains noise.
