---
output: html_document
---

<!-- wrapping up -->

#### Additional Coverage

You can learn more about signals, noise, signal-to-noise ratios, and signal averaging in Chapter 10.3 of *Analytical Chemistry 2.1,* which you can access using this [link](https://chem.libretexts.org/Bookshelves/Analytical_Chemistry/Analytical_Chemistry_2.1_(Harvey)/10%3A_Spectroscopic_Methods/10.03%3A_UV_Vis_and_IR_Spectroscopy). You can learn more about both signal averaging and smoothing filters in Chapter 10 of *Chemometrics with R,*" which you can access using this [link](https://chem.libretexts.org/Bookshelves/Analytical_Chemistry/Chemometrics_Using_R_(Harvey)/10%3A_Cleaning_Up_Data). The original paper on Savitzky-Golay smoothing is "Smoothing and Differentiation of Data by Simplified Least Squares Procedures," *Analytical Chemistry*, *36*, 1627--1639, which is available at this [link](https://doi.org/10.1021/ac60214a047). You can explore signal averaging and smoothing filters using the javascript applet available [here](http://195.134.76.37/applets/AppletSmooth/Appl_Smooth2.html).

#### Details on the Data Set in this Module

The spectra in all activities, except for Activity 2, use a commerical food coloring that contains the FD&C dyes Blue 1 and Red 40, as the analyte. A portion of the stock solution was diluted until the absorbance was between 0.02 and 0.03 au. Spectra were recorded using a Vernier SpectroVis Plus spectrophotometer and LoggerPro software. A full spectrum was recorded for each of 70+ consecutive scans, stored, and exported as a single .csv file. This file was trimmed to the first 64 spectra for use in this module.

#### Why Did We Use Synthetic Data in Activity 2?

One limitation to working with real spectra is that we cannot separate the signal from the noise so that we can examine them separately, Synthetic data allows us to do this by separately creating the signal and the noise, and then adding them together to create a noisy signal. The figure on the upper right shows the original spectrum from Activity 2 as the pure signal, the pure noise, and the resulting noisy signal.

#### Can We Use a Smoothing Filter Several Times on the Same Data?

In a word: yes. The figure on the lower right shows, in blue, one spectrum of the blue dye and the results, in magenta, of applying a 15-point moving average filter five times. Care is needed to avoid distortions due to over-smoothing.
